# Site settings
port: 4000
title: Atom-k9 JRubyArt for Atom
email: mamba2928@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
   JRubyArt is a ruby wrapper for processing-3.2.1+ this package enables running of JRubyArt sketches (watch mode) from the Atom editor
   ruby-processing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ruby-processing.github.io/atom-k9"
urls:
  bugs: https://github.com/ruby-processing/atom-k9/issues
  github: https://github.com/ruby-processing/atom-k9/
twitter_username: monkstoneT
github_username:  monkstone

syntax-highlighting:
  enabled: true
# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
